# Generated by Django 4.1.7 on 2023-04-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='logo/')),
                ('trend', models.BooleanField(blank=True, default=False, null=True)),
                ('pupolar', models.BooleanField(blank=True, default=False, null=True)),
                ('topview', models.BooleanField(blank=True, default=False, null=True)),
                ('new', models.BooleanField(blank=True, default=False, null=True)),
                ('recently', models.BooleanField(blank=True, default=False, null=True)),
                ('live', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
