# Generated by Django 4.1.7 on 2023-04-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='live',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='new',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='pupolar',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='recently',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='topview',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='trend',
        ),
    ]
