# Generated by Django 4.1.7 on 2023-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='visitcount',
            field=models.IntegerField(default=0),
        ),
    ]
