# Generated by Django 4.1.7 on 2023-04-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='poster/')),
                ('typeof', models.CharField(max_length=255)),
                ('studio', models.CharField(max_length=255)),
                ('dateAired', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=100)),
                ('scores', models.BigIntegerField(default=0)),
                ('rating', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
            },
        ),
    ]
