# Generated by Django 4.1.7 on 2023-04-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Полнометражный', 'verbose_name_plural': 'Полномеьражные'},
        ),
    ]
