# Generated by Django 4.1.7 on 2023-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='restrictions',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
