# Generated by Django 4.1.7 on 2023-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
