# Generated by Django 4.1.7 on 2023-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
