# Generated by Django 4.1.7 on 2023-04-05 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_video_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='player',
            new_name='file',
        ),
    ]
