# Generated by Django 4.1.7 on 2023-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_rename_player_video_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Полнометражный', 'verbose_name_plural': 'Полнометражные'},
        ),
        migrations.AddField(
            model_name='movie',
            name='liveaction',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popular',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
