# Generated by Django 4.1.7 on 2023-04-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_movie_options_movie_liveaction_movie_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
    ]
