# Generated by Django 4.1.7 on 2023-04-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Полнометражный', 'verbose_name_plural': 'Полнометражные'},
        ),
    ]
