# Generated by Django 4.2 on 2023-04-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('TVS', 'TV Series'), ('Пол.метр.', 'Полнометражный'), ('Кор.метр.', 'Короткометражный')], max_length=50)),
                ('studios', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('quality', models.CharField(choices=[('HD', 'HD'), ('FHD', 'FHD'), ('LOW', 'LOW'), ('2k', '2K')], max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.products')),
                ('userObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.categories')),
                ('productObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstLowSmallImagePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small3', to='kinoapp.products')),
                ('firstTopSmallImagePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small1', to='kinoapp.products')),
                ('leftBigImagePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big1', to='kinoapp.products')),
                ('rightBigImagePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='big2', to='kinoapp.products')),
                ('secondLowSmallImagePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small4', to='kinoapp.products')),
                ('secondTopSmallImagePO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='small2', to='kinoapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.news')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.products')),
                ('userObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
