# Generated by Django 4.2 on 2023-04-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinoapp', '0002_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsdetails',
            options={'verbose_name': 'Новости детали', 'verbose_name_plural': 'Новости детали'},
        ),
        migrations.AlterModelOptions(
            name='ourblog',
            options={'verbose_name': 'Картинки блога', 'verbose_name_plural': 'Картинки блога'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='productscategories',
            options={'verbose_name': 'Категории произведений', 'verbose_name_plural': 'Категории произведений'},
        ),
        migrations.AlterModelOptions(
            name='productsimages',
            options={'verbose_name': 'Картинки произведений', 'verbose_name_plural': 'Картинки произведений'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
    ]
