# Generated by Django 4.2 on 2023-04-29 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinoapp', '0002_products_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsdetails',
            options={'verbose_name': 'Новости детали', 'verbose_name_plural': 'Новости детали'},
        ),
        migrations.AlterModelOptions(
            name='ourblog',
            options={'verbose_name': 'Картинки блога', 'verbose_name_plural': 'Картинки блога'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Произведения', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='productscategories',
            options={'verbose_name': 'Категории произведений', 'verbose_name_plural': 'Категории произведений'},
        ),
        migrations.AlterModelOptions(
            name='productsimages',
            options={'verbose_name': 'Картинки произведений', 'verbose_name_plural': 'Картинки произведений'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинг'},
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queueNumber', models.IntegerField(default=1)),
                ('productObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinoapp.products')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдер',
            },
        ),
    ]
